CQCL/tket-json-rs

Cargo.toml
Found the MSRV with `cargo-msrv`. 1.59 fails because of the `dep:` prefixes in `Cargo.toml`
=> Update dependencies, set MSRV

Cargo.toml, README.md, RELEASES.md, src/circuit_json.rs, src/lib.rs, src/optype.rs, src/pytket.rs
Copied what I could from TKET's doc.
There is no math rendering for the op definitions, we'll need to add something like [katex_doc](https://docs.rs/katex-doc/0.1.0/katex_doc/) later.
Also deletes the outdated `tket2ops` feature (#11).
=> doc: Add missing docs everywhere

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/pr-title.yml, Cargo.toml, README.md
- Add dependabot
- Enable merge queue triggers
- Enable conventional commit PR name checks
Also pushes MSRV to 1.70
=> ci: Bring in CI updates from other repos

src/circuit_json.rs, src/optype.rs
- Expand box types to support more (but not all) of the current possible pytket box types.
- Re-order the OpType variants to match those of the boxes.
=> feat: expand box types and match order

.github/workflows/issue.yml
Copy the config over from hugr.
Resolves #19
=> chore: Add priorities to Jira issues upon creation

src/pytket.rs
`from_tket1` and `to_tket1` now receive the Global Interpreter Lock (GIL) as a parameter rather than adquiring it internally.
This is more composable in cases where we want to reuse the GIL.
The locking methods are kept as utility functions.
BREAKING CHANGE: Renamed `SerialCircuit::to_tket1` to `to_tket1_with_gil`, and `_from_tket1` to `from_tket1_with_gil`.
=> feat!: non-locking python conversion calls

src/circuit_json.rs, src/optype.rs
=> feat: ToffoliBox encoding

src/circuit_json.rs, src/lib.rs, src/opbox.rs
Adds a new `opbox.rs` file and moves `OpBox` there, to keep the code clean.
=> refactor: Move `OpBox` to a new module

src/circuit_json.rs, src/opbox.rs, src/optype.rs
Adds the missing optypes listed in #36.
Fixes #30.
=> fix: Add missing OpTypes

src/optype.rs, tests/poetry.lock
Closes #41 
There isn't much info on these gates on the pytket side, so the docs here are a bit lacking.
=> feat: Add GPI, GPI2, and AAMS gates

src/circuit_json.rs
Some fields were not marked `pub`lic, so they couldn't be accessed after deserialisation
=> fix: Make some missing fields pub

src/opbox.rs, src/optype.rs
Closes #46 
drive-by: Fix clippy lint due to missing doc
=> fix: Add missing `CnRx` `CnRz` ops

src/optype.rs
add support to prevent failure when getting circuits with legacy tk1 optype
=> feat: handle legacy tk1 optype 

src/circuit_json.rs, src/optype.rs, tests/data/classical.json, tests/data/diagonal-box.json, tests/roundtrip.rs
Closes #53 
drive-by: Add missing `data` field to Operation ([schema](https://github.com/CQCL/tket/blob/a47578ec5d79bb5caf23ef2edee3f587bc3c7d14/schemas/circuit_v1.json#L283-L286)).
drive-by: Remove `created_qubits`/`discarded_qubits` from the test files. Those fields are not in the schema.
drive-by: Mark more structs as `non_exhaustive`, so in the future a change like this does not have to be breaking.
BREAKING CHANGE: Added `data` and `classical` fields to `Operation`. Marked some structs/enums as non_exhaustive.
=> feat!: Classical op params

src/circuit_json.rs, src/opbox.rs
Updated ToffoliBox permutation type to match tket schema and nexus dataclasses. This inconsistency caused failures when getting circuits that include a ToffoliBox from the database.
=> fix: Update ToffoliBox permutation type

src/circuit_json.rs, tests/data/wasm.json, tests/roundtrip.rs
BREAKING CHANGE: Added a `number_of_ws` field to `SerialCircuit`
=> feat!: Add support for WASM operations

src/circuit_json.rs
Some helpers to convert between parameter types without too much boilerplate.
I wanted to add `ToOwned` instances or something similar, but most trait implementations clash with blanket impls, so these are just struct methods.
=> feat: `map_params` helpers on the parametric structs

.github/dependabot.yml
`pyo3` and `pythonize` need to be updated together, as there can only be one `pyo3` version in the dependency tree.
Adds a dependabot update group for them, as well as the group config we setup for `tket2`.
=> ci: Dependabot groups

.github/workflows/missing-ops.yml
Updates the missing ops slack notifier to run daily, so we find the errors quicker.
We use the new workflow from https://github.com/CQCL/hugrverse-actions/pull/18 to add a one-week timeout, so we don't spam the chat.
The notification step was actually broken on `main`. This PR adds a `continue-on-error` flag on the test job so it doesn't get skipped the notification when it fails.
=> ci: Quicker missing op notifications

src/circuit_json.rs
[pytket `1.7.3`](https://tket.quantinuum.com/api-docs/changelog.html#october-2022) added `created`/`discarded_qubits` fields to the circuit serialization, but we never added them here.
BREAKING CHANGE: Made `SerialCircuit` non exhaustive.
=> feat!: `created/discarded_qubits` circuit attribute

.github/workflows/ci.yml, Cargo.toml, src/circuit_json.rs, src/lib.rs, src/opbox.rs, src/register.rs
Renames `Register` to `ElementId`, and adds two wrappers `Bit` and `Qubit` to use where appropriate.
Since we are doing a breaking change, I moved the related definitions to a new file to keep things clean.
BREAKING CHANGE: `Register` renamed to `ElementId`, `Qubit` and `Bit`
BREAKING CHANGE: Moved some definitions from `::circuit_json` to `::register`
BREAKING CHANGE: Bumped MSRV to `rust 1.75`
=> feat!: Rename `Register` and cleanup definitions

README.md
#89 bumped the MSRV to 1.75, but didn't update the README badge
=> chore: Update MSRV badge in README

src/circuit_json.rs, src/opbox.rs, src/optype.rs
Closes #67 
BREAKING CHANGE: Renamed `circuit_json::CompositeGate` to `CustomGate`
=> feat!: Support old `Composite` alias for `CustomGate`

.github/workflows/ci.yml, .github/workflows/semver-checks.yml
Fixes errors when running the workflow for dependabot
See https://github.com/CQCL/hugr/pull/1661
=> ci: Call `semver_checks` from `pull_request_target`

.github/workflows/missing-ops.yml
Looks like this job has been failing since the last time I changed it -.-
I ways trying to pas an `env` var into the `secrets` of the workflow call,
which caused a syntax error.
https://github.com/CQCL/tket-json-rs/actions/runs/12348388888
=> ci: Fix invalid syntax in missing ops workflow

src/clexpr.rs, src/clexpr/operator.rs
Adds some comments, pointing to where the local indices are being defined.
=> docs: Clearup clexpr argument index documentation

Cargo.lock, Cargo.toml, src/opbox.rs
I'd prefer to avoid making `uuid` a public dependency, so add some constructors here.
=> feat: Method for generating BoxIDs
